# -*- coding: utf-8 -*-
"""memorybot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TXVZhMM0RadQcW-UwKZ2YUh8EZQ05DZx
"""

!pip install -q -U langgraph langchain-google-genai langgraph-checkpoint-sqlite

import os
from getpass import getpass
from google.colab import userdata

api_key = ""
try:
    api_key = userdata.get("GOOGLE_API_KEY").strip()
except Exception:
    pass

if not api_key:
    api_key = getpass("Paste your Google AI Studio API key: ").strip()

os.environ["GOOGLE_API_KEY"] = api_key
print("Google API key loaded.")

import sqlite3
from typing import Annotated
from typing_extensions import TypedDict

from langchain_google_genai import ChatGoogleGenerativeAI
from langgraph.graph import StateGraph, START, END
from langgraph.graph.message import add_messages
from langgraph.checkpoint.sqlite import SqliteSaver


class State(TypedDict):
    messages: Annotated[list, add_messages]


# "gemini-flash-latest" always points to the current Flash model
llm = ChatGoogleGenerativeAI(model="gemini-flash-latest")

print("Model test:", llm.invoke("Reply with the single word: ready").text)


def chatbot(state: State):
    return {"messages": [llm.invoke(state["messages"])]}


graph_builder = StateGraph(State)
graph_builder.add_node("chatbot", chatbot)
graph_builder.add_edge(START, "chatbot")
graph_builder.add_edge("chatbot", END)

conn = sqlite3.connect(":memory:", check_same_thread=False)
memory = SqliteSaver(conn)

graph = graph_builder.compile(checkpointer=memory)
print("Chatbot is ready.")

from IPython.display import Image, display

try:
    display(Image(graph.get_graph().draw_mermaid_png()))
except Exception:
    print(graph.get_graph().draw_ascii())

config = {"configurable": {"thread_id": "1"}}

result = graph.invoke(
    {"messages": [("user", "Hi, I'm Kartik. Explain LangGraph in one line.")]},
    config,
)
print("Assistant:", result["messages"][-1].text)

result = graph.invoke({"messages": [("user", "What's my name?")]}, config)
print("Assistant:", result["messages"][-1].text)

config = {"configurable": {"thread_id": "1"}}  # change the id to start a fresh conversation

while True:
    user_input = input("User: ")
    if user_input.strip().lower() in ["quit", "exit", "q"]:
        print("Goodbye!")
        break

    try:
        for event in graph.stream({"messages": [("user", user_input)]}, config):
            for value in event.values():
                print("Assistant:", value["messages"][-1].text)
    except Exception as e:
        print(f"Error: {e}")
        break

for m in graph.get_state(config).values["messages"]:
    m.pretty_print()